services:
  - type: web
    name: hensonsignature
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma db push && npx prisma db seed && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
